const db = require('../db/database');

const rawMovies = [
  {
    Title: 'The Shawshank Redemption',
    Year: '1994',
    Rated: 'R',
    Released: '14 Oct 1994',
    Runtime: '142 min',
    Genre: 'Drama',
    Director: 'Frank Darabont',
    Writer: 'Stephen King, Frank Darabont',
    Actors: 'Tim Robbins, Morgan Freeman, Bob Gunton',
    Plot: 'A banker convicted of uxoricide forms a friendship over a quarter century with a hardened convict, while maintaining his innocence and trying to remain hopeful through simple compassion.',
    Language: 'English',
    Country: 'United States',
    Awards: 'Nominated for 7 Oscars. 21 wins & 42 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '9.3/10' },
      { Source: 'Rotten Tomatoes', Value: '89%' },
      { Source: 'Metacritic', Value: '82/100' },
    ],
    Trailer_url: 'https://youtu.be/PLl99DlL6b4?si=yPk1dch7uUHOPKwG',
    Metascore: '82',
    imdbRating: '9.3',
    imdbVotes: '3,015,278',
    imdbID: 'tt0111161',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$28,767,189',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Inception',
    Year: '2010',
    Rated: 'PG-13',
    Released: '16 Jul 2010',
    Runtime: '148 min',
    Genre: 'Action, Adventure, Sci-Fi',
    Director: 'Christopher Nolan',
    Writer: 'Christopher Nolan',
    Actors: 'Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page',
    Plot: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.',
    Language: 'English, Japanese, French',
    Country: 'United States, United Kingdom',
    Awards: 'Won 4 Oscars. 159 wins & 220 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.8/10' },
      { Source: 'Rotten Tomatoes', Value: '87%' },
      { Source: 'Metacritic', Value: '74/100' },
    ],
    Trailer_url: 'https://youtu.be/YoHD9XEInc0?si=4s_9RpCE_959DMYL',
    Metascore: '74',
    imdbRating: '8.8',
    imdbVotes: '2,658,716',
    imdbID: 'tt1375666',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$292,587,330',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Cars',
    Year: '2006',
    Rated: 'G',
    Released: '09 Jun 2006',
    Runtime: '116 min',
    Genre: 'Animation, Adventure, Comedy',
    Director: 'John Lasseter, Joe Ranft',
    Writer: 'John Lasseter, Joe Ranft, Jorgen Klubien',
    Actors: 'Owen Wilson, Bonnie Hunt, Paul Newman',
    Plot: "On the way to the biggest race of his life, a hotshot rookie race car gets stranded in a rundown town and learns that winning isn't everything in life.",
    Language: 'English, Italian, Japanese, Yiddish',
    Country: 'United States',
    Awards: 'Nominated for 2 Oscars. 28 wins & 34 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMTg5NzY0MzA2MV5BMl5BanBnXkFtZTYwNDc3NTc2._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '7.3/10' },
      { Source: 'Rotten Tomatoes', Value: '74%' },
      { Source: 'Metacritic', Value: '73/100' },
    ],
    Trailer_url: 'https://youtu.be/W_H7_tDHFE8?si=gZvRQqgnrP1wWwQJ',
    Metascore: '73',
    imdbRating: '7.3',
    imdbVotes: '493,848',
    imdbID: 'tt0317219',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$244,082,982',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'The Godfather',
    Year: '1972',
    Rated: 'R',
    Released: '24 Mar 1972',
    Runtime: '175 min',
    Genre: 'Crime, Drama',
    Director: 'Francis Ford Coppola',
    Writer: 'Mario Puzo, Francis Ford Coppola',
    Actors: 'Marlon Brando, Al Pacino, James Caan',
    Plot: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
    Language: 'English, Italian, Latin',
    Country: 'United States',
    Awards: 'Won 3 Oscars. 31 wins & 31 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BNGEwYjgwOGQtYjg5ZS00Njc1LTk2ZGEtM2QwZWQ2NjdhZTE5XkEyXkFqcGc@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '9.2/10' },
      { Source: 'Rotten Tomatoes', Value: '97%' },
      { Source: 'Metacritic', Value: '100/100' },
    ],
    Trailer_url: 'https://youtu.be/UaVTIH8mujA?si=IXUn1M7AwP6a4251',
    Metascore: '100',
    imdbRating: '9.2',
    imdbVotes: '2,108,592',
    imdbID: 'tt0068646',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$136,381,073',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'The Dark Knight',
    Year: '2008',
    Rated: 'PG-13',
    Released: '18 Jul 2008',
    Runtime: '152 min',
    Genre: 'Action, Crime, Drama',
    Director: 'Christopher Nolan',
    Writer: 'Jonathan Nolan, Christopher Nolan, David S. Goyer',
    Actors: 'Christian Bale, Heath Ledger, Aaron Eckhart',
    Plot: 'When a menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman, James Gordon and Harvey Dent must work together to put an end to the madness.',
    Language: 'English, Mandarin',
    Country: 'United States, United Kingdom',
    Awards: 'Won 2 Oscars. 164 wins & 165 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '9.0/10' },
      { Source: 'Rotten Tomatoes', Value: '94%' },
      { Source: 'Metacritic', Value: '84/100' },
    ],
    Trailer_url: 'https://youtu.be/EXeTwQWrcwY?si=KrmiZgsxsz11js2L',
    Metascore: '84',
    imdbRating: '9.0',
    imdbVotes: '2,997,696',
    imdbID: 'tt0468569',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$534,987,076',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Forrest Gump',
    Year: '1994',
    Rated: 'PG-13',
    Released: '06 Jul 1994',
    Runtime: '142 min',
    Genre: 'Drama, Romance',
    Director: 'Robert Zemeckis',
    Writer: 'Winston Groom, Eric Roth',
    Actors: 'Tom Hanks, Robin Wright, Gary Sinise',
    Plot: "The history of the United States from the 1950s to the '70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.",
    Language: 'English',
    Country: 'United States',
    Awards: 'Won 6 Oscars. 51 wins & 74 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BNDYwNzVjMTItZmU5YS00YjQ5LTljYjgtMjY2NDVmYWMyNWFmXkEyXkFqcGc@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.8/10' },
      { Source: 'Rotten Tomatoes', Value: '75%' },
      { Source: 'Metacritic', Value: '82/100' },
    ],
    Trailer_url: 'https://youtu.be/Mj9IA9tTfio?si=rp8nQB_ufr2WDQwm',
    Metascore: '82',
    imdbRating: '8.8',
    imdbVotes: '2,342,884',
    imdbID: 'tt0109830',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$330,455,270',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
];

const movies = rawMovies.map((movie) => ({
  imdb_id: movie.imdbID,
  title: movie.Title,
  description: movie.Plot,
  length_minutes: parseInt(movie.Runtime), // convert '148 min' to number
  release_year: parseInt(movie.Year),
  director: movie.Director,
  poster_url: movie.Poster,
  trailer_url:
    movie.Trailer_url ||
    `https://www.youtube.com/results?search_query=${encodeURIComponent(
      movie.Title
    )}+trailer`,
  genre: movie.Genre,
}));

const stmt = db.prepare(`
  INSERT INTO movies (imdb_id, title, description, length_minutes, release_year, director, poster_url, trailer_url, genre)
  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`);

movies.forEach((movie) => {
  stmt.run(
    movie.imdb_id,
    movie.title,
    movie.description,
    movie.length_minutes,
    movie.release_year,
    movie.director,
    movie.poster_url,
    movie.trailer_url,
    movie.genre
  );
});

console.log('✅ Filmer har lagts in i databasen');
